# Modify the MOM overlay.
edit_overlay 155 23EC400 23FC054 23FC058 0 0
replace_overlay 155 ../ASM/Overlay_155.bin

# Edit filenames.
rename 0 000_galaxyShrinkPlatformFrame.bmd
rename 1 001_galaxyShrinkPlatform.bmd
rename 2 002_galaxyShrinkPlatform.kcl
rename 3 003_silverCoin.bmd
rename 4 004_invisibleWall.bmd
rename 5 005_invisibleWall.kcl
rename 6 006_berry.bmd
rename 7 007_berryStem.bmd
rename 8 008_riding.bca
rename 9 009_coloredGoomba.bmd
rename A 010_coloredGoomba.btp
rename B 011_noteBlock.bmd
rename C 012_noteBlock.kcl
rename D 013_shyGuy.bmd
rename E 014_shyGuyWait.bca
rename F 015_shyGuyWalk.bca
rename 10 016_shyGuyRun.bca
rename 11 017_shyGuyFreeze.bca
rename 12 018_lstar.bmd
rename 13 019_lsWait.bca
rename 14 020_lsLaunch.bca
rename 15 021_magikoopa.bmd
rename 16 022_kamella.bmd
rename 17 023_magikoopaAppear.bca
rename 18 024_magikoopaWave.bca
rename 19 025_magikoopaShoot.bca
rename 1A 026_magikoopaPoof.bca
rename 1B 027_magikoopaWait.bca
rename 1C 028_magikoopaHurt.bca
rename 1D 029_magikoopaDefeat.bca
rename 1E 030_magikoopaMagic.bmd
rename 1F 031_magikoopaMagic.btp
rename 20 032_icicle.bmd
rename 21 033_yoshiNPC.bmd
rename 22 034_yoshiNPCWait.bca
rename 23 035_coloredPipe.bmd
rename 24 036_coloredPipe.kcl
rename 25 037_characterBlockMario.bmd
rename 26 038_characterBlockLuigi.bmd
rename 27 039_characterBlockWario.bmd
rename 28 040_characterBlockYoshi.bmd
rename 29 041_characterBlockAll.kcl
rename 2A 042_characterBlockAll.bca
rename 2B 043_characterBlockTransMario.bmd
rename 2C 044_characterBlockTransLuigi.bmd
rename 2D 045_characterBlockTransWario.bmd
rename 2E 046_characterBlockTransYoshi.bmd
rename 2F 047_characterBlockTransAll.bca
rename 30 048_saveBlock.bmd
rename 31 049_saveBlock.btp
rename 32 050_saveBlock.kcl
rename 33 051_starChip.bmd
rename 34 052_doorBlocker.bmd
rename 35 053_doorBlocker.kcl
rename 36 054_coloredCoin.bmd
rename 37 055_coloredToad.bmd
rename 38 056_coloredToad.btp
rename 39 057_coloredToadWait_1.bca
rename 3A 058_coloredToadWait_2.bca
rename 3B 059_peachNPC.bmd
rename 3C 060_peachNPC.bca
rename 3D 061_peachNPC.bca
rename 3E 062_blueIceBlock.bmd
rename 3F 063_blueIceBlock.kcl
rename 40 064_megaBlock.bmd
rename 41 065_megaBlock.kcl
rename 42 066_customBlockYellow.bmd
rename 43 067_customBlockRed.bmd
rename 44 068_customBlockRedTrans.bmd
rename 45 069_customBlock.kcl
rename 46 070_customBlockTrans.bca
rename 47 071_treasureChest.bmd
rename 48 072_treasureChest.bca
rename 49 073_thwomp.bmd
rename 4A 074_thwomp.btp
rename 4B 075_thwomp.kcl
rename 4C 076_thwompMagma.bmd
rename 4D 077_thwompGiga.bmd
rename 4E 078_thwompGiga.kcl
rename 4F 079_toxBox.bmd
rename 50 080_toxBox.kcl
rename 51 081_toxBoxSwitch.bmd
rename 52 082_toxBoxSwitch.kcl
rename 53 083_toxBoxPlayer.bmd
rename 54 084_toxBoxPlayer.btp
rename 55 085_toxBoxFlower.bmd
rename 56 086_coloredGoomba_2.bmd

# Replace assets.
replace 0 ../Objects/GalaxyShrinkPlatform/ModelCollision/galaxyShrinkPlatformFrame.bmd
replace 1 ../Objects/GalaxyShrinkPlatform/ModelCollision/galaxyShrinkPlatform.bmd
replace 2 ../Objects/GalaxyShrinkPlatform/ModelCollision/galaxyShrinkPlatform.kcl
replace 3 ../Objects/SilverCoin/Model/silverCoin.bmd
replace 4 ../Objects/InvisibleWall/ModelCollision/invisibleWall.bmd
replace 5 ../Objects/InvisibleWall/ModelCollision/invisibleWall.kcl
replace 6 ../Objects/Berry/Model/berry.bmd
replace 7 ../Objects/Berry/Model/berryStem.bmd
replace 8 ../Objects/YoshiRide/Anim/riding.bca
replace 9 ../Objects/ColoredGoombas/Model/kuribo_model.bmd
replace A ../Objects/ColoredGoombas/TexAnim/kuribo_colorsw.btp
replace B ../Objects/Noteblock/ModelCollision/noteblock.bmd
replace C ../Objects/Noteblock/ModelCollision/noteblock.kcl
replace D ../Objects/ShyGuy/Model/shyGuy.bmd
replace E ../Objects/ShyGuy/Anim/shyGuyWait.bca
replace F ../Objects/ShyGuy/Anim/shyGuyWalk.bca
replace 10 ../Objects/ShyGuy/Anim/shyGuyRun.bca
replace 11 ../Objects/ShyGuy/Anim/shyGuyFreeze.bca
replace 12 ../Objects/LaunchStar/Model/lstar.bmd
replace 13 ../Objects/LaunchStar/Anim/lsWait.bca
replace 14 ../Objects/LaunchStar/Anim/lsLaunch.bca
replace 15 ../Objects/Magikoopa/Model/magikoopa.bmd
replace 16 ../Objects/Magikoopa/Model/kamella.bmd
replace 17 ../Objects/Magikoopa/Anim/magikoopaAppear.bca
replace 18 ../Objects/Magikoopa/Anim/magikoopaWave.bca
replace 19 ../Objects/Magikoopa/Anim/magikoopaShoot.bca
replace 1A ../Objects/Magikoopa/Anim/magikoopaPoof.bca
replace 1B ../Objects/Magikoopa/Anim/magikoopaWait.bca
replace 1C ../Objects/Magikoopa/Anim/magikoopaHurt.bca
replace 1D ../Objects/Magikoopa/Anim/magikoopaDefeat.bca
replace 1E ../Objects/Magikoopa/Model/magic.bmd
replace 1F ../Objects/Magikoopa/TexAnim/magic.btp
replace 20 ../Objects/FallingIcicle/Model/icicle.bmd
replace 21 ../Objects/YoshiNPC/Model/yoshi_model.bmd
replace 22 ../Objects/YoshiNPC/Anim/Y_wait.bca
replace 23 ../Objects/ColoredPipe/ModelCollision/obj_dokan.bmd
replace 24 ../Objects/ColoredPipe/ModelCollision/obj_dokan.kcl
replace 25 ../Objects/CharacterBlock/ModelCollision/obj_cap_box_m.bmd
replace 26 ../Objects/CharacterBlock/ModelCollision/obj_cap_box_l.bmd
replace 27 ../Objects/CharacterBlock/ModelCollision/obj_cap_box_w.bmd
replace 28 ../Objects/CharacterBlock/ModelCollision/obj_cap_box_y.bmd
replace 29 ../Objects/CharacterBlock/ModelCollision/hatena_box.kcl
replace 2A ../Objects/CharacterBlock/Anim/hatena_karabox_empty.bca
replace 2B ../Objects/CharacterBlock/ModelCollision/hatena_karabox_m.bmd
replace 2C ../Objects/CharacterBlock/ModelCollision/hatena_karabox_l.bmd
replace 2D ../Objects/CharacterBlock/ModelCollision/hatena_karabox_w.bmd
replace 2E ../Objects/CharacterBlock/ModelCollision/hatena_karabox_y.bmd
replace 3F ../Objects/CharacterBlock/Anim/hatena_karabox.bca
replace 30 ../Objects/SaveBlock/ModelCollision/saveBlock.bmd
replace 31 ../Objects/SaveBlock/TexAnim/saveBlock.btp
replace 32 ../Objects/SaveBlock/ModelCollision/saveBlock.kcl
replace 33 ../Objects/StarChip/Model/starChip.bmd
replace 34 ../Objects/DoorBlocker/ModelCollision/door_blocker.bmd
replace 35 ../Objects/DoorBlocker/ModelCollision/door_blocker.kcl
replace 36 ../Objects/ColoredCoin/Model/coloredCoin.bmd
replace 37 ../Objects/ColoredToadNPC/Model/toad.bmd
replace 38 ../Objects/ColoredToadNPC/TexAnim/toad.btp
replace 39 ../Objects/ColoredToadNPC/Anim/toad_wait1.bca
replace 3A ../Objects/ColoredToadNPC/Anim/toad_wait2.bca
replace 3B ../Objects/PeachNPC/Model/peach_low.bmd
replace 3C ../Objects/PeachNPC/Anim/peach_wait.bca
replace 3D ../Objects/PeachNPC/Anim/peach_ed_wait.bca
replace 3E ../Objects/BlueIceBlock/ModelCollision/ice_block_ll.bmd
replace 3F ../Objects/BlueIceBlock/ModelCollision/ice_block_ll.kcl
replace 40 ../Objects/MegaBlock/ModelCollision/star_block.bmd
replace 41 ../Objects/MegaBlock/ModelCollision/star_block.kcl
replace 42 ../Objects/CustomBlock/ModelCollision/obj_hatena_y_box.bmd
replace 43 ../Objects/CustomBlock/ModelCollision/hatena_box.bmd
replace 44 ../Objects/CustomBlock/ModelCollision/hatena_karabox.bmd
replace 45 ../Objects/CustomBlock/ModelCollision/hatena_box.kcl
replace 46 ../Objects/CustomBlock/Anim/hatena_karabox.bca
replace 47 ../Objects/TreasureChest/Model/t_box.bmd
replace 48 ../Objects/TreasureChest/Anim/t_box_open.bca
replace 49 ../Objects/Thwomp/ModelCollision/thwomp.bmd
replace 4A ../Objects/Thwomp/TexAnim/thwomp.btp
replace 4B ../Objects/Thwomp/ModelCollision/thwomp.kcl
replace 4C ../Objects/Thwomp/ModelCollision/thwompMagma.bmd
replace 4D ../Objects/Thwomp/ModelCollision/thwompGiga.bmd
replace 4E ../Objects/Thwomp/ModelCollision/thwomp.kcl
replace 4F ../Objects/ToxBox/ModelCollision/onimasu.bmd
replace 50 ../Objects/ToxBox/ModelCollision/onimasu.kcl
replace 51 ../Objects/ToxBox/ModelCollision/onimasu_switch.bmd
replace 52 ../Objects/ToxBox/ModelCollision/onimasu_switch.kcl
replace 53 ../Objects/ToxBox/ModelCollision/player.bmd
replace 54 ../Objects/ToxBox/TexAnim/player.btp
replace 55 ../Objects/ToxBox/ModelCollision/flower.bmd	
replace 56 ../Objects/ColoredGoombas/Model/kuribo_model_2.bmd